[supervisord]
nodaemon=true

[program:node]
directory=/app/node-backend
command=node index.js
autostart=true
autorestart=true

[program:flask]
directory=/app/python-service
command=gunicorn -b 0.0.0.0:5000 chart_service:app
autostart=true
autorestart=true
